languageCode = 'en-gb'
title = 'Linux-Gamer'
theme = "ananke"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"

######################### Default Parameters ###########################
[params]
# logo
logo = "images/navlogo.png"
logoWidth = 121
logoHeight = 50
# favicon
favicon = "images/favicon.png"
# meta data
author = "Linux Gamer"
description = "Gamer, Artist, Gamedev, YouTuber"
# homepage main section
mainSections = ["posts"]
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = ""
rssLimit = 20
# search *** true or false (if Search is disable Menu will align in Right) ***
search = true

header_search_layout = "expanded" # "expanded" or "popupable"
# Menu align *** "left", "right" or "center" (if Search is disable Menu will align in Right) ***
menu_align = "center"
# Blog-details page sidebar
sidebar = "left" # Sidebar value ("left", "right" or false)

######################## Site Variables #########################
[params.variables]
# Color Variables
primary_color = "#47c4f1"
secondary_color = "#9AC4F8"
text_color = "#666666"
text_color_dark = "#222222"
body_color = "#fff"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
light = "#F8F8F8"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "JetBrainsMono:wght@400;700"
secondary_font = ""
icon_font = "Font Awesome 5 Free"

############################## Social Site ##########################
[[params.social]]
icon = "fab fa-youtube" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://youtube.com/c/UCbBtLFxKBpcwt85EoP0kXRg"
[[params.social]]
icon = "fab fa-twitter" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://twitter.com/The_LinuxGamer"
[[params.social]]
icon = "fab fa-github" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://github.com/linux-gamer"
[[params.social]]
[[params.social]]
icon = "fas fa-rss" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://christitus.com/rss"

####################### Banner #######################################
[Languages.en.banner]
bg_image = "images/bannerbackground.png"
title = "<strong>Linux Gamer</strong><br>How To Articles, <br>Image Downloads,<br> Tech Guides."
image = "images/operating systems.jpg"

######################## About Me Widget ###############################
[Languages.en.about_me]
title = "Linux-Gamer"
bio = ""

[[params.social_profile]]
icon = "fab fa-twitter" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://twitter.com/The_LinuxGamer"
[[params.social_profile]]
icon = "fab fa-github" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://github.com/linux-gamer"
[[params.social_profile]]
icon = "fab fa-youtube" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://www.youtube.com/channel/UCbBtLFxKBpcwt85EoP0kXRg"


############################# English - Main Menu ########################
[[Languages.en.menu.main]]
weight = 1
url = "/"
name = "Home"

[[Languages.en.menu.main]]
    name = "Latest Videos"
    url = "https://www.cttstore.com/community/topics/27931"
